export interface ProductSpecs {
  // GPU fields
  vram?: string;
  vramType?: "GDDR6" | "GDDR6X" | "HBM3" | "HBM2e";
  chipset?: string; // RTX 50-series, 40-series, etc.
  cuda?: string;
  tensor?: string;
  
  // CPU fields
  cores?: string;
  threads?: string;
  socket?: string; // LGA1700, AM5, etc.
  boostClock?: string;
  
  // Motherboard fields
  formFactor?: "ATX" | "E-ATX" | "Micro-ATX" | "Mini-ITX";
  memorySlots?: string;
  
  // Common fields
  tdp?: string;
  clock?: string;
  memory?: string;
  bandwidth?: string;
  tflops?: string;
  architecture?: string;
  process?: string;
  channels?: string;
}

export interface Merchant {
  name: "Amazon" | "eBay" | "AliExpress";
  price: number;
  link: string;
}

export interface Product {
  id: string;
  name: string;
  category: "GPU" | "CPU" | "Workstation" | "MiniPC" | "Cooling" | "Storage" | "Motherboard" | "RAM" | "PSU";
  brand: string;
  description: string;
  price: number; // Lowest price among merchants
  msrp: number;
  imageUrl: string;
  specs: ProductSpecs;
  merchants: Merchant[];
  tags: string[];
  recommended: boolean;
  availability: "In Stock" | "Pre-order" | "Coming Soon";
  aiScore?: number;
}

const IMAGE_BY_CATEGORY: Record<Product["category"], string> = {
  GPU: "/hardware-placeholder.svg",
  CPU: "/hardware-placeholder.svg",
  Motherboard: "/hardware-placeholder.svg",
  RAM: "/hardware-placeholder.svg",
  Storage: "/hardware-placeholder.svg",
  PSU: "/hardware-placeholder.svg",
  Cooling: "/hardware-placeholder.svg",
  Workstation: "/hardware-placeholder.svg",
  MiniPC: "/hardware-placeholder.svg",
};

// High-resolution product-specific images (400x400px minimum)
const PRODUCT_IMAGES: Record<string, string> = {
  // RTX 50 Series
  "rtx-5090": "https://assets.nvidia.com/assets/images/nvidia-geforce-rtx-5090-og.jpg",
  "rtx-5080": "https://assets.nvidia.com/assets/images/nvidia-geforce-rtx-5080-og.jpg",
  "rtx-5070-ti": "https://assets.nvidia.com/assets/images/nvidia-geforce-rtx-5070-ti-og.jpg",
  "rtx-5070": "https://assets.nvidia.com/assets/images/nvidia-geforce-rtx-5070-og.jpg",
  // RTX 40 Series
  "rtx-4090": "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/graphics-cards/rtx-4090/geforce-rtx-4090-shop-630-d@2x.png",
  "rtx-4080-super": "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/graphics-cards/rtx-4080-super/geforce-rtx-4080-super-shop-630-d@2x.png",
  "rtx-4070-ti-super": "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/graphics-cards/rtx-4070-ti-super/geforce-rtx-4070-ti-super-shop-630-d@2x.png",
  "rtx-4070-super": "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/graphics-cards/rtx-4070-super/geforce-rtx-4070-super-shop-630-d@2x.png",
  // RTX 30 Series
  "rtx-3090-ti": "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ampere/rtx-3090-ti/3090-ti-shop-630-d@2x.png",
  "rtx-3090": "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ampere/rtx-3090/geforce-rtx-3090-shop-630-d@2x.png",
  "rtx-3080-ti": "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ampere/rtx-3080-ti/3080-ti-shop-630-d@2x.png",
  "rtx-3080-12gb": "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ampere/rtx-3080/3080-shop-630-d@2x.png",
  "rtx-3070-ti": "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ampere/rtx-3070-ti/rtx-3070-ti-shop-630-d@2x.png",
  "rtx-3060-12gb": "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ampere/rtx-3060/rtx-3060-shop-630-d@2x.png",
  // Quadro/Professional
  "quadro-rtx-8000": "https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/quadro/rtx-8000/quadro-rtx-8000-shop-630-d@2x.png",
  "quadro-rtx-6000": "https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/quadro/rtx-6000/quadro-rtx-6000-shop-630-d@2x.png",
  "quadro-rtx-5000": "https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/quadro/rtx-5000/quadro-rtx-5000-shop-630-d@2x.png",
  "rtx-a6000-ada": "https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/rtx-6000-ada/rtx-6000-ada-shop-630-d@2x.png",
  "rtx-a5000": "https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/rtx-a5000/rtx-a5000-shop-630-d@2x.png",
  "rtx-a4000": "https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/rtx-a4000/rtx-a4000-shop-630-d@2x.png",
  // Datacenter
  "nvidia-a100-80gb": "https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/a100/nvidia-a100-og.jpg",
  "nvidia-h100-pcie": "https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/h100/nvidia-h100-og.jpg",
  "l40s": "https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/l40s/nvidia-l40s-og.jpg",
  "rtx-6000-ada-sff": "https://www.nvidia.com/content/dam/en-zz/Solutions/design-visualization/rtx-6000-ada/rtx-6000-ada-shop-630-d@2x.png",
  // AMD Threadripper
  "threadripper-pro-7995wx": "https://www.amd.com/system/files/2023-10/amd-ryzen-threadripper-pro-7000-wx-1260x709.png",
  "threadripper-pro-7985wx": "https://www.amd.com/system/files/2023-10/amd-ryzen-threadripper-pro-7000-wx-1260x709.png",
  "threadripper-pro-7975wx": "https://www.amd.com/system/files/2023-10/amd-ryzen-threadripper-pro-7000-wx-1260x709.png",
  "threadripper-pro-7965wx": "https://www.amd.com/system/files/2023-10/amd-ryzen-threadripper-pro-7000-wx-1260x709.png",
  "threadripper-7980x": "https://www.amd.com/system/files/2023-10/amd-ryzen-threadripper-7000-1260x709.png",
  "threadripper-7970x": "https://www.amd.com/system/files/2023-10/amd-ryzen-threadripper-7000-1260x709.png",
  "threadripper-7960x": "https://www.amd.com/system/files/2023-10/amd-ryzen-threadripper-7000-1260x709.png",
  // Intel Xeon
  "xeon-w9-3495x": "https://www.intel.com/content/dam/www/public/us/en/images/products/processors/xeon/hero-xeon-w-3400-series.png",
  "xeon-w7-2495x": "https://www.intel.com/content/dam/www/public/us/en/images/products/processors/xeon/hero-xeon-w-2400-series.png",
  "xeon-gold-6430": "https://www.intel.com/content/dam/www/public/us/en/images/products/processors/xeon/4th-gen-xeon-scalable-family.png",
  // Intel Core
  "core-i9-14900ks": "https://www.intel.com/content/dam/www/public/us/en/images/products/processors/core/14th-gen-core-i9-14900ks.png",
  "core-i9-14900k": "https://www.intel.com/content/dam/www/public/us/en/images/products/processors/core/14th-gen-core-i9-14900k.png",
  "core-ultra-9-285k": "https://www.intel.com/content/dam/www/public/us/en/images/products/processors/core-ultra/hero-core-ultra-200s-series.png",
  // AMD Ryzen
  "ryzen-9-9950x": "https://www.amd.com/system/files/2024-08/amd-ryzen-9000-series-1260x709.png",
  "ryzen-9-7950x3d": "https://www.amd.com/system/files/2023-02/amd-ryzen-7000-series-7950x3d-1260x709.png",
  "ryzen-9-7950x": "https://www.amd.com/system/files/2022-08/amd-ryzen-7000-series-1260x709.png",
  // Motherboards
  "asus-pro-ws-trx50-sage": "https://dlcdnwebimgs.asus.com/gain/7f8e8e2e-6c8e-4b8e-9f1e-8b0b0e6b9b9b/w692/h472",
  "gigabyte-trx50-aero-d": "https://www.gigabyte.com/FileUpload/Global/KeyFeature/2331/images/mb.png",
  "asus-pro-ws-w790-ace": "https://dlcdnwebimgs.asus.com/gain/7f8e8e2e-6c8e-4b8e-9f1e-8b0b0e6b9b9b/w692/h472",
  "supermicro-x13swa-tf": "https://www.supermicro.com/sites/default/files/2023-02/X13SWA-TF_3D.png",
  "asus-rog-crosshair-x670e-hero": "https://dlcdnwebimgs.asus.com/gain/7f8e8e2e-6c8e-4b8e-9f1e-8b0b0e6b9b9b/w692/h472",
  "msi-meg-x670e-godlike": "https://storage-asset.msi.com/global/picture/image/feature/mb/MEG-X670E-GODLIKE/hero.png",
  "asus-rog-maximus-z790-hero": "https://dlcdnwebimgs.asus.com/gain/7f8e8e2e-6c8e-4b8e-9f1e-8b0b0e6b9b9b/w692/h472",
  "gigabyte-z890-aorus-master": "https://www.gigabyte.com/FileUpload/Global/KeyFeature/2331/images/mb.png",
  // RAM
  "corsair-dominator-titanium-128-6400": "https://cwsmkt.corsair.com/responsive-images/1379/72c2d8c4-6b5b-4e8a-9c2d-1f3e8a9b0c1d/dom-titanium.png",
  "gskill-z5-rgb-128-6000": "https://www.gskill.com/upload_images/ftr/trident-z5-rgb.png",
  "kingston-server-premier-256-ecc": "https://www.kingston.com/siteassets/images/large/product_memory_server-premier.png",
  "crucial-pro-256-5600": "https://www.crucial.com/content/dam/crucial/products/memory/dram/crucial-pro/crucial-pro-ddr5-udimm.png",
  "samsung-rdimm-256-4800": "https://images.samsung.com/is/image/samsung/p5/global/business/semiconductor/products/dram/Samsung_RDIMM_4800.png",
  "teamgroup-tcreate-128-7200": "https://www.teamgroupinc.com/en/upload/product_color/20230815101745.png",
  // Storage
  "samsung-990-pro-4tb": "https://images.samsung.com/is/image/samsung/p6pim/us/2307/gallery/us-2307-990-pro-heatsink-1tb-536972-536972-536972-536972-536972-536972-536972-536972-536972-536972-NL-535156617?$624_624_PNG$",
  "crucial-t705-4tb": "https://www.crucial.com/content/dam/crucial/ssd-products/t705/images/crucial-t705-ssd-front.png",
  // PSU
  "corsair-axi-1600i": "https://cwsmkt.corsair.com/responsive-images/1379/72c2d8c4-6b5b-4e8a-9c2d-1f3e8a9b0c1d/axi1600i.png",
  "seasonic-prime-tx-1300": "https://seasonic.com/pub/media/catalog/product/cache/17d4f96c5b9f4d34b7b8c357e1b5d5b0/p/r/prime-tx-1300.png",
  // Cooling
  "arctic-liquid-freezer-iii-420": "https://www.arctic.de/wp-content/uploads/2023/09/liquid-freezer-iii-420.png",
  "noctua-nh-d15-g2": "https://noctua.at/img/product/nh_d15_g2/nh_d15_g2_1.png",
};

function getProductImage(product: ProductSeed): string {
  // First try product-specific image
  if (product.id && PRODUCT_IMAGES[product.id]) {
    return PRODUCT_IMAGES[product.id];
  }
  // Fall back to category image
  return IMAGE_BY_CATEGORY[product.category];
}

interface ProductSeed extends Omit<Product, "merchants" | "imageUrl" | "recommended" | "availability"> {
  query?: string;
  imageUrl?: string;
  recommended?: boolean;
  availability?: Product["availability"];
}

function createMerchants(query: string, price: number): Merchant[] {
  const encoded = encodeURIComponent(query).replace(/%20/g, "+");
  const ebayPrice = Math.max(10, Math.round(price * 0.95));
  const aliPrice = Math.max(10, Math.round(price * 0.92));

  return [
    { name: "Amazon", price, link: `https://www.amazon.com/s?k=${encoded}` },
    { name: "eBay", price: ebayPrice, link: `https://www.ebay.com/sch/i.html?_nkw=${encoded}` },
    { name: "AliExpress", price: aliPrice, link: `https://www.aliexpress.com/wholesale?SearchText=${encoded}` },
  ];
}

const seedProducts: ProductSeed[] = [
  {
    id: "rtx-5090",
    name: "NVIDIA GeForce RTX 5090",
    category: "GPU",
    brand: "NVIDIA",
    description: "Blackwell flagship for large-model training and high-throughput inference.",
    price: 1999,
    msrp: 1999,
    specs: { vram: "32GB GDDR7", cuda: "21,760", tensor: "680", tdp: "450W", tflops: "125 FP16", architecture: "Blackwell" },
    tags: ["RTX 50", "Flagship", "LLM"],
    aiScore: 100,
  },
  {
    id: "rtx-5080",
    name: "NVIDIA GeForce RTX 5080",
    category: "GPU",
    brand: "NVIDIA",
    description: "High-end Blackwell GPU for multi-agent inference nodes.",
    price: 1199,
    msrp: 1199,
    specs: { vram: "16GB GDDR7", cuda: "10,752", tensor: "336", tdp: "320W", tflops: "57 FP16", architecture: "Blackwell" },
    tags: ["RTX 50", "Inference"],
    aiScore: 91,
  },
  {
    id: "rtx-5070-ti",
    name: "NVIDIA GeForce RTX 5070 Ti",
    category: "GPU",
    brand: "NVIDIA",
    description: "Balanced Blackwell tier for creator AI workstations.",
    price: 799,
    msrp: 799,
    specs: { vram: "16GB GDDR7", cuda: "8,960", tensor: "280", tdp: "285W", tflops: "45 FP16", architecture: "Blackwell" },
    tags: ["RTX 50", "Prosumer"],
    aiScore: 86,
  },
  {
    id: "rtx-5070",
    name: "NVIDIA GeForce RTX 5070",
    category: "GPU",
    brand: "NVIDIA",
    description: "Efficient mid-high model serving GPU.",
    price: 599,
    msrp: 599,
    specs: { vram: "12GB GDDR7", cuda: "7,680", tensor: "240", tdp: "250W", tflops: "37 FP16", architecture: "Blackwell" },
    tags: ["RTX 50", "Value"],
    aiScore: 82,
  },
  {
    id: "rtx-4090",
    name: "NVIDIA GeForce RTX 4090",
    category: "GPU",
    brand: "NVIDIA",
    description: "Reference card for local LLM and diffusion work.",
    price: 1599,
    msrp: 1599,
    specs: { vram: "24GB GDDR6X", cuda: "16,384", tensor: "512", tdp: "450W", tflops: "82.6 FP16", architecture: "Ada Lovelace" },
    tags: ["RTX 40", "24GB VRAM"],
    aiScore: 98,
  },
  {
    id: "rtx-4080-super",
    name: "NVIDIA GeForce RTX 4080 SUPER",
    category: "GPU",
    brand: "NVIDIA",
    description: "Strong inference performer with better perf/watt than 30-series.",
    price: 999,
    msrp: 999,
    specs: { vram: "16GB GDDR6X", cuda: "10,240", tensor: "320", tdp: "320W", tflops: "52.2 FP16", architecture: "Ada Lovelace" },
    tags: ["RTX 40", "Inference"],
    aiScore: 89,
  },
  {
    id: "rtx-4070-ti-super",
    name: "NVIDIA GeForce RTX 4070 Ti SUPER",
    category: "GPU",
    brand: "NVIDIA",
    description: "Cost-efficient 16GB Ada card for mixed workloads.",
    price: 799,
    msrp: 799,
    specs: { vram: "16GB GDDR6X", cuda: "8,448", tensor: "264", tdp: "285W", tflops: "40 FP16", architecture: "Ada Lovelace" },
    tags: ["RTX 40", "16GB VRAM"],
    aiScore: 84,
  },
  {
    id: "rtx-4070-super",
    name: "NVIDIA GeForce RTX 4070 SUPER",
    category: "GPU",
    brand: "NVIDIA",
    description: "Entry point for efficient CUDA acceleration.",
    price: 599,
    msrp: 599,
    specs: { vram: "12GB GDDR6X", cuda: "7,168", tensor: "224", tdp: "220W", tflops: "35.5 FP16", architecture: "Ada Lovelace" },
    tags: ["RTX 40", "Budget AI"],
    aiScore: 78,
  },
  {
    id: "rtx-3090-ti",
    name: "NVIDIA GeForce RTX 3090 Ti",
    category: "GPU",
    brand: "NVIDIA",
    description: "Ampere flagship with 24GB VRAM and NVLink support.",
    price: 1099,
    msrp: 1999,
    specs: { vram: "24GB GDDR6X", cuda: "10,752", tensor: "336", tdp: "450W", tflops: "40 FP16", architecture: "Ampere" },
    tags: ["RTX 30", "NVLink"],
    aiScore: 83,
  },
  {
    id: "rtx-3090",
    name: "NVIDIA GeForce RTX 3090",
    category: "GPU",
    brand: "NVIDIA",
    description: "Popular 24GB model for budget-friendly fine-tuning.",
    price: 899,
    msrp: 1499,
    specs: { vram: "24GB GDDR6X", cuda: "10,496", tensor: "328", tdp: "350W", tflops: "35.6 FP16", architecture: "Ampere" },
    tags: ["RTX 30", "Used Market"],
    aiScore: 80,
  },
  {
    id: "rtx-3080-ti",
    name: "NVIDIA GeForce RTX 3080 Ti",
    category: "GPU",
    brand: "NVIDIA",
    description: "Ampere high-end card for inferencing and medium training.",
    price: 699,
    msrp: 1199,
    specs: { vram: "12GB GDDR6X", cuda: "10,240", tensor: "320", tdp: "350W", tflops: "34.1 FP16", architecture: "Ampere" },
    tags: ["RTX 30", "High-End"],
    aiScore: 74,
  },
  {
    id: "rtx-3080-12gb",
    name: "NVIDIA GeForce RTX 3080 12GB",
    category: "GPU",
    brand: "NVIDIA",
    description: "Efficient CUDA throughput for developer workstations.",
    price: 549,
    msrp: 799,
    specs: { vram: "12GB GDDR6X", cuda: "8,960", tensor: "280", tdp: "350W", tflops: "29.8 FP16", architecture: "Ampere" },
    tags: ["RTX 30", "Mainstream"],
    aiScore: 70,
  },
  {
    id: "rtx-3070-ti",
    name: "NVIDIA GeForce RTX 3070 Ti",
    category: "GPU",
    brand: "NVIDIA",
    description: "Compact Ampere option for small AI rigs.",
    price: 449,
    msrp: 599,
    specs: { vram: "8GB GDDR6X", cuda: "6,144", tensor: "192", tdp: "290W", tflops: "21.7 FP16", architecture: "Ampere" },
    tags: ["RTX 30", "Compact"],
    aiScore: 62,
  },
  {
    id: "rtx-3060-12gb",
    name: "NVIDIA GeForce RTX 3060 12GB",
    category: "GPU",
    brand: "NVIDIA",
    description: "Entry CUDA card with useful 12GB VRAM footprint.",
    price: 289,
    msrp: 329,
    specs: { vram: "12GB GDDR6", cuda: "3,584", tensor: "112", tdp: "170W", tflops: "13 FP16", architecture: "Ampere" },
    tags: ["RTX 30", "Entry"],
    aiScore: 58,
  },
  {
    id: "quadro-rtx-8000",
    name: "NVIDIA Quadro RTX 8000",
    category: "GPU",
    brand: "NVIDIA",
    description: "Legacy enterprise card with 48GB ECC memory.",
    price: 4499,
    msrp: 5499,
    specs: { vram: "48GB GDDR6 ECC", cuda: "4,608", tensor: "576", tdp: "295W", tflops: "32.6 FP16", architecture: "Turing" },
    tags: ["Quadro", "Enterprise", "ECC"],
    aiScore: 79,
  },
  {
    id: "quadro-rtx-6000",
    name: "NVIDIA Quadro RTX 6000",
    category: "GPU",
    brand: "NVIDIA",
    description: "Professional card with 24GB ECC VRAM.",
    price: 2899,
    msrp: 3999,
    specs: { vram: "24GB GDDR6 ECC", cuda: "4,608", tensor: "576", tdp: "260W", tflops: "32.6 FP16", architecture: "Turing" },
    tags: ["Quadro", "Professional"],
    aiScore: 72,
  },
  {
    id: "quadro-rtx-5000",
    name: "NVIDIA Quadro RTX 5000",
    category: "GPU",
    brand: "NVIDIA",
    description: "Reliable workstation GPU for CAD + AI mixed pipelines.",
    price: 1599,
    msrp: 2299,
    specs: { vram: "16GB GDDR6", cuda: "3,072", tensor: "384", tdp: "265W", tflops: "22.2 FP16", architecture: "Turing" },
    tags: ["Quadro", "Workstation"],
    aiScore: 65,
  },
  {
    id: "rtx-a6000-ada",
    name: "NVIDIA RTX 6000 Ada Generation",
    category: "GPU",
    brand: "NVIDIA",
    description: "48GB Ada workstation accelerator for enterprise inferencing.",
    price: 6799,
    msrp: 6799,
    specs: { vram: "48GB GDDR6 ECC", cuda: "18,176", tensor: "568", tdp: "300W", tflops: "91.1 FP16", architecture: "Ada Lovelace" },
    tags: ["RTX Ada", "Enterprise", "48GB"],
    aiScore: 97,
  },
  {
    id: "rtx-a5000",
    name: "NVIDIA RTX A5000",
    category: "GPU",
    brand: "NVIDIA",
    description: "Ampere workstation card with 24GB ECC VRAM.",
    price: 2299,
    msrp: 2499,
    specs: { vram: "24GB GDDR6 ECC", cuda: "8,192", tensor: "256", tdp: "230W", tflops: "54.2 FP16", architecture: "Ampere" },
    tags: ["A-Series", "ECC"],
    aiScore: 81,
  },
  {
    id: "rtx-a4000",
    name: "NVIDIA RTX A4000",
    category: "GPU",
    brand: "NVIDIA",
    description: "Efficient single-slot workstation option with 16GB VRAM.",
    price: 1099,
    msrp: 1249,
    specs: { vram: "16GB GDDR6 ECC", cuda: "6,144", tensor: "192", tdp: "140W", tflops: "38.7 FP16", architecture: "Ampere" },
    tags: ["A-Series", "Single Slot"],
    aiScore: 73,
  },
  {
    id: "nvidia-a100-80gb",
    name: "NVIDIA A100 80GB PCIe",
    category: "GPU",
    brand: "NVIDIA",
    description: "Datacenter GPU optimized for transformer training.",
    price: 11999,
    msrp: 11999,
    specs: { vram: "80GB HBM2e", cuda: "6,912", tensor: "432", tdp: "300W", tflops: "312 Tensor", architecture: "Ampere" },
    tags: ["A-Series", "Datacenter", "HBM"],
    aiScore: 95,
  },
  {
    id: "nvidia-h100-pcie",
    name: "NVIDIA H100 80GB PCIe",
    category: "GPU",
    brand: "NVIDIA",
    description: "Hopper accelerator for enterprise model training at scale.",
    price: 24999,
    msrp: 24999,
    specs: { vram: "80GB HBM3", cuda: "14,592", tensor: "456", tdp: "350W", tflops: "989 Tensor", architecture: "Hopper" },
    tags: ["Hopper", "Datacenter", "HBM3"],
    aiScore: 99,
  },
  {
    id: "l40s",
    name: "NVIDIA L40S",
    category: "GPU",
    brand: "NVIDIA",
    description: "Datacenter inference GPU with high memory and throughput.",
    price: 8999,
    msrp: 8999,
    specs: { vram: "48GB GDDR6", cuda: "18,176", tensor: "568", tdp: "350W", tflops: "91 FP16", architecture: "Ada Lovelace" },
    tags: ["Datacenter", "Inference"],
    aiScore: 93,
  },
  {
    id: "rtx-6000-ada-sff",
    name: "NVIDIA RTX 6000 Ada SFF",
    category: "GPU",
    brand: "NVIDIA",
    description: "Small-form-factor Ada workstation accelerator.",
    price: 4299,
    msrp: 4299,
    specs: { vram: "20GB GDDR6 ECC", cuda: "7,424", tensor: "232", tdp: "210W", tflops: "39 FP16", architecture: "Ada Lovelace" },
    tags: ["Ada", "SFF"],
    aiScore: 77,
  },

  {
    id: "threadripper-pro-7995wx",
    name: "AMD Ryzen Threadripper PRO 7995WX",
    category: "CPU",
    brand: "AMD",
    description: "96-core workstation CPU built for data pipeline and simulation heavy tasks.",
    price: 4999,
    msrp: 4999,
    specs: { cores: "96", threads: "192", clock: "2.5 / 5.1 GHz", tdp: "350W", memory: "8-Channel DDR5", socket: "sTR5" },
    tags: ["Threadripper", "PRO"],
    aiScore: 97,
  },
  {
    id: "threadripper-pro-7985wx",
    name: "AMD Ryzen Threadripper PRO 7985WX",
    category: "CPU",
    brand: "AMD",
    description: "64-core workstation-class chip with massive IO.",
    price: 3799,
    msrp: 3799,
    specs: { cores: "64", threads: "128", clock: "3.2 / 5.1 GHz", tdp: "350W", memory: "8-Channel DDR5", socket: "sTR5" },
    tags: ["Threadripper", "PRO"],
    aiScore: 92,
  },
  {
    id: "threadripper-pro-7975wx",
    name: "AMD Ryzen Threadripper PRO 7975WX",
    category: "CPU",
    brand: "AMD",
    description: "32-core CPU ideal for multi-GPU creator stations.",
    price: 2499,
    msrp: 2499,
    specs: { cores: "32", threads: "64", clock: "4.0 / 5.3 GHz", tdp: "350W", memory: "8-Channel DDR5", socket: "sTR5" },
    tags: ["Threadripper", "PRO"],
    aiScore: 87,
  },
  {
    id: "threadripper-pro-7965wx",
    name: "AMD Ryzen Threadripper PRO 7965WX",
    category: "CPU",
    brand: "AMD",
    description: "24-core workstation model with enterprise ECC support.",
    price: 1699,
    msrp: 1699,
    specs: { cores: "24", threads: "48", clock: "4.2 / 5.3 GHz", tdp: "350W", memory: "8-Channel DDR5", socket: "sTR5" },
    tags: ["Threadripper", "PRO"],
    aiScore: 84,
  },
  {
    id: "threadripper-7980x",
    name: "AMD Ryzen Threadripper 7980X",
    category: "CPU",
    brand: "AMD",
    description: "HEDT 64-core CPU for workstation creators and ML engineers.",
    price: 2999,
    msrp: 2999,
    specs: { cores: "64", threads: "128", clock: "3.2 / 5.1 GHz", tdp: "350W", memory: "4-Channel DDR5", socket: "sTR5" },
    tags: ["Threadripper", "HEDT"],
    aiScore: 90,
  },
  {
    id: "threadripper-7970x",
    name: "AMD Ryzen Threadripper 7970X",
    category: "CPU",
    brand: "AMD",
    description: "32-core HEDT chip balancing frequency and lane count.",
    price: 2499,
    msrp: 2499,
    specs: { cores: "32", threads: "64", clock: "4.0 / 5.3 GHz", tdp: "350W", memory: "4-Channel DDR5", socket: "sTR5" },
    tags: ["Threadripper", "HEDT"],
    aiScore: 85,
  },
  {
    id: "threadripper-7960x",
    name: "AMD Ryzen Threadripper 7960X",
    category: "CPU",
    brand: "AMD",
    description: "24-core HEDT processor for heavy multitasking workloads.",
    price: 1499,
    msrp: 1499,
    specs: { cores: "24", threads: "48", clock: "4.2 / 5.3 GHz", tdp: "350W", memory: "4-Channel DDR5", socket: "sTR5" },
    tags: ["Threadripper", "HEDT"],
    aiScore: 81,
  },
  {
    id: "xeon-w9-3495x",
    name: "Intel Xeon w9-3495X",
    category: "CPU",
    brand: "Intel",
    description: "56-core workstation CPU with ECC and large memory support.",
    price: 5889,
    msrp: 5889,
    specs: { cores: "56", threads: "112", clock: "1.9 / 4.8 GHz", tdp: "350W", memory: "8-Channel DDR5 ECC", socket: "LGA4677" },
    tags: ["Xeon", "Workstation"],
    aiScore: 89,
  },
  {
    id: "xeon-w7-2495x",
    name: "Intel Xeon w7-2495X",
    category: "CPU",
    brand: "Intel",
    description: "24-core Xeon alternative for workstation reliability.",
    price: 2189,
    msrp: 2189,
    specs: { cores: "24", threads: "48", clock: "2.5 / 4.8 GHz", tdp: "225W", memory: "4-Channel DDR5 ECC", socket: "LGA4677" },
    tags: ["Xeon", "ECC"],
    aiScore: 79,
  },
  {
    id: "xeon-gold-6430",
    name: "Intel Xeon Gold 6430",
    category: "CPU",
    brand: "Intel",
    description: "Server-grade CPU for dense inferencing and virtualization.",
    price: 2199,
    msrp: 2199,
    specs: { cores: "32", threads: "64", clock: "2.1 / 3.4 GHz", tdp: "270W", memory: "8-Channel DDR5 ECC", socket: "LGA4677" },
    tags: ["Xeon", "Server"],
    aiScore: 76,
  },
  {
    id: "core-i9-14900ks",
    name: "Intel Core i9-14900KS",
    category: "CPU",
    brand: "Intel",
    description: "High-frequency desktop flagship for low-latency compile and preprocessing.",
    price: 699,
    msrp: 699,
    specs: { cores: "24", threads: "32", clock: "3.2 / 6.2 GHz", tdp: "150W", memory: "Dual-Channel DDR5", socket: "LGA1700" },
    tags: ["Core i9", "Desktop"],
    aiScore: 82,
  },
  {
    id: "core-i9-14900k",
    name: "Intel Core i9-14900K",
    category: "CPU",
    brand: "Intel",
    description: "Mainstream high-end desktop CPU for mixed creative/AI use.",
    price: 589,
    msrp: 589,
    specs: { cores: "24", threads: "32", clock: "3.2 / 6.0 GHz", tdp: "125W", memory: "Dual-Channel DDR5", socket: "LGA1700" },
    tags: ["Core i9", "Desktop"],
    aiScore: 79,
  },
  {
    id: "core-ultra-9-285k",
    name: "Intel Core Ultra 9 285K",
    category: "CPU",
    brand: "Intel",
    description: "Arrow Lake desktop part with NPU support.",
    price: 589,
    msrp: 589,
    specs: { cores: "24", threads: "24", clock: "3.7 / 5.7 GHz", tdp: "125W", memory: "Dual-Channel DDR5", socket: "LGA1851" },
    tags: ["Core Ultra", "NPU"],
    aiScore: 78,
  },
  {
    id: "ryzen-9-9950x",
    name: "AMD Ryzen 9 9950X",
    category: "CPU",
    brand: "AMD",
    description: "Zen 5 flagship for high IPC AI preprocessing workflows.",
    price: 649,
    msrp: 649,
    specs: { cores: "16", threads: "32", clock: "4.3 / 5.7 GHz", tdp: "170W", memory: "Dual-Channel DDR5", socket: "AM5" },
    tags: ["Ryzen 9", "Zen 5"],
    aiScore: 86,
  },
  {
    id: "ryzen-9-7950x3d",
    name: "AMD Ryzen 9 7950X3D",
    category: "CPU",
    brand: "AMD",
    description: "3D V-Cache model with strong mixed gaming and inference behavior.",
    price: 599,
    msrp: 699,
    specs: { cores: "16", threads: "32", clock: "4.2 / 5.7 GHz", tdp: "120W", memory: "Dual-Channel DDR5", socket: "AM5" },
    tags: ["Ryzen 9", "3D V-Cache"],
    aiScore: 80,
  },
  {
    id: "ryzen-9-7950x",
    name: "AMD Ryzen 9 7950X",
    category: "CPU",
    brand: "AMD",
    description: "Reliable 16-core Zen 4 workstation favorite.",
    price: 549,
    msrp: 699,
    specs: { cores: "16", threads: "32", clock: "4.5 / 5.7 GHz", tdp: "170W", memory: "Dual-Channel DDR5", socket: "AM5" },
    tags: ["Ryzen 9", "Zen 4"],
    aiScore: 78,
  },

  {
    id: "asus-pro-ws-trx50-sage",
    name: "ASUS Pro WS TRX50-SAGE WIFI",
    category: "Motherboard",
    brand: "ASUS",
    description: "Workstation board with four x16 slots for Threadripper builds.",
    price: 1299,
    msrp: 1299,
    specs: { socket: "sTR5", memory: "DDR5 ECC", channels: "Quad/Octa", architecture: "TRX50" },
    tags: ["TRX50", "Workstation"],
    aiScore: 93,
  },
  {
    id: "gigabyte-trx50-aero-d",
    name: "Gigabyte TRX50 AERO D",
    category: "Motherboard",
    brand: "Gigabyte",
    description: "Creator-focused TRX50 board for high-bandwidth GPU arrays.",
    price: 899,
    msrp: 899,
    specs: { socket: "sTR5", memory: "DDR5 ECC", channels: "Quad", architecture: "TRX50" },
    tags: ["TRX50", "Creator"],
    aiScore: 86,
  },
  {
    id: "asus-pro-ws-w790-ace",
    name: "ASUS Pro WS W790-ACE",
    category: "Motherboard",
    brand: "ASUS",
    description: "Xeon W workstation platform with ECC and extensive PCIe layout.",
    price: 999,
    msrp: 999,
    specs: { socket: "LGA4677", memory: "DDR5 ECC", channels: "Quad/Octa", architecture: "W790" },
    tags: ["W790", "Xeon"],
    aiScore: 88,
  },
  {
    id: "supermicro-x13swa-tf",
    name: "Supermicro X13SWA-TF",
    category: "Motherboard",
    brand: "Supermicro",
    description: "Enterprise W790 motherboard with remote management features.",
    price: 1199,
    msrp: 1199,
    specs: { socket: "LGA4677", memory: "DDR5 ECC", channels: "Quad/Octa", architecture: "W790" },
    tags: ["W790", "IPMI"],
    aiScore: 84,
  },
  {
    id: "asus-rog-crosshair-x670e-hero",
    name: "ASUS ROG Crosshair X670E Hero",
    category: "Motherboard",
    brand: "ASUS",
    description: "Top-tier AM5 board for Ryzen 9 class CPUs.",
    price: 649,
    msrp: 699,
    specs: { socket: "AM5", memory: "DDR5", channels: "Dual", architecture: "X670E" },
    tags: ["AM5", "Enthusiast"],
    aiScore: 83,
  },
  {
    id: "msi-meg-x670e-godlike",
    name: "MSI MEG X670E GODLIKE",
    category: "Motherboard",
    brand: "MSI",
    description: "Premium AM5 board with high VRM headroom.",
    price: 899,
    msrp: 1299,
    specs: { socket: "AM5", memory: "DDR5", channels: "Dual", architecture: "X670E" },
    tags: ["AM5", "Premium"],
    aiScore: 82,
  },
  {
    id: "asus-rog-maximus-z790-hero",
    name: "ASUS ROG Maximus Z790 Hero",
    category: "Motherboard",
    brand: "ASUS",
    description: "High-end Intel board for Core i9 LGA1700 builds.",
    price: 629,
    msrp: 629,
    specs: { socket: "LGA1700", memory: "DDR5", channels: "Dual", architecture: "Z790" },
    tags: ["LGA1700", "Overclock"],
    aiScore: 80,
  },
  {
    id: "gigabyte-z890-aorus-master",
    name: "Gigabyte Z890 AORUS Master",
    category: "Motherboard",
    brand: "Gigabyte",
    description: "LGA1851 platform option for Core Ultra desktop systems.",
    price: 599,
    msrp: 599,
    specs: { socket: "LGA1851", memory: "DDR5", channels: "Dual", architecture: "Z890" },
    tags: ["LGA1851", "Core Ultra"],
    aiScore: 78,
  },

  {
    id: "corsair-dominator-titanium-128-6400",
    name: "Corsair Dominator Titanium 128GB (4x32GB) DDR5-6400",
    category: "RAM",
    brand: "Corsair",
    description: "High-speed large-capacity kit for local model development.",
    price: 599,
    msrp: 649,
    specs: { memory: "128GB (4x32GB)", clock: "6400 MT/s", architecture: "DDR5", tdp: "1.4V" },
    tags: ["128GB", "DDR5"],
    aiScore: 88,
  },
  {
    id: "gskill-z5-rgb-128-6000",
    name: "G.Skill Trident Z5 RGB 128GB (4x32GB) DDR5-6000",
    category: "RAM",
    brand: "G.Skill",
    description: "AM5-friendly high-density DDR5 kit.",
    price: 529,
    msrp: 579,
    specs: { memory: "128GB (4x32GB)", clock: "6000 MT/s", architecture: "DDR5", tdp: "1.35V" },
    tags: ["128GB", "AM5"],
    aiScore: 86,
  },
  {
    id: "kingston-server-premier-256-ecc",
    name: "Kingston Server Premier 256GB (8x32GB) DDR5-5600 ECC",
    category: "RAM",
    brand: "Kingston",
    description: "Workstation ECC kit for heavy-memory data science builds.",
    price: 899,
    msrp: 999,
    specs: { memory: "256GB (8x32GB)", clock: "5600 MT/s", architecture: "DDR5 ECC", channels: "8-channel" },
    tags: ["256GB", "ECC"],
    aiScore: 91,
  },
  {
    id: "crucial-pro-256-5600",
    name: "Crucial Pro 256GB (4x64GB) DDR5-5600",
    category: "RAM",
    brand: "Crucial",
    description: "Large-capacity non-ECC option for creator rigs.",
    price: 799,
    msrp: 849,
    specs: { memory: "256GB (4x64GB)", clock: "5600 MT/s", architecture: "DDR5" },
    tags: ["256GB", "High Density"],
    aiScore: 84,
  },
  {
    id: "samsung-rdimm-256-4800",
    name: "Samsung 256GB (8x32GB) DDR5-4800 RDIMM ECC",
    category: "RAM",
    brand: "Samsung",
    description: "Registered ECC kit for Xeon and Threadripper PRO systems.",
    price: 1049,
    msrp: 1099,
    specs: { memory: "256GB (8x32GB)", clock: "4800 MT/s", architecture: "DDR5 RDIMM ECC", channels: "8-channel" },
    tags: ["256GB", "RDIMM"],
    aiScore: 90,
  },
  {
    id: "teamgroup-tcreate-128-7200",
    name: "TEAMGROUP T-Create Expert 128GB (4x32GB) DDR5-7200",
    category: "RAM",
    brand: "TEAMGROUP",
    description: "High-frequency dense kit for fast data transformation tasks.",
    price: 649,
    msrp: 699,
    specs: { memory: "128GB (4x32GB)", clock: "7200 MT/s", architecture: "DDR5" },
    tags: ["128GB", "High Speed"],
    aiScore: 82,
  },

  {
    id: "samsung-990-pro-4tb",
    name: "Samsung 990 PRO 4TB NVMe",
    category: "Storage",
    brand: "Samsung",
    description: "Fast PCIe 4.0 SSD for model files and datasets.",
    price: 299,
    msrp: 349,
    specs: { memory: "4TB", bandwidth: "7,450 MB/s", architecture: "PCIe 4.0 x4" },
    tags: ["NVMe", "High Speed"],
    aiScore: 87,
  },
  {
    id: "crucial-t705-4tb",
    name: "Crucial T705 4TB NVMe",
    category: "Storage",
    brand: "Crucial",
    description: "PCIe 5.0 SSD for extreme ingest and checkpoint throughput.",
    price: 449,
    msrp: 499,
    specs: { memory: "4TB", bandwidth: "14,100 MB/s", architecture: "PCIe 5.0 x4" },
    tags: ["NVMe", "PCIe 5.0"],
    aiScore: 90,
  },

  {
    id: "corsair-axi-1600i",
    name: "Corsair AX1600i",
    category: "PSU",
    brand: "Corsair",
    description: "1600W Titanium PSU for multi-GPU AI workstations.",
    price: 599,
    msrp: 699,
    specs: { tdp: "1600W", architecture: "80+ Titanium", memory: "ATX 3.0" },
    tags: ["1600W", "Titanium"],
    aiScore: 93,
  },
  {
    id: "seasonic-prime-tx-1300",
    name: "Seasonic PRIME TX-1300",
    category: "PSU",
    brand: "Seasonic",
    description: "High-efficiency 1300W unit for dual high-end GPU configurations.",
    price: 439,
    msrp: 489,
    specs: { tdp: "1300W", architecture: "80+ Titanium", memory: "ATX 3.0" },
    tags: ["1300W", "Dual GPU"],
    aiScore: 88,
  },

  {
    id: "arctic-liquid-freezer-iii-420",
    name: "ARCTIC Liquid Freezer III 420",
    category: "Cooling",
    brand: "ARCTIC",
    description: "420mm AIO recommended for high-TDP workstation CPUs.",
    price: 169,
    msrp: 179,
    specs: { tdp: "420W", architecture: "AIO", memory: "420mm radiator" },
    tags: ["AIO", "High TDP"],
    aiScore: 84,
  },
  {
    id: "noctua-nh-d15-g2",
    name: "Noctua NH-D15 G2",
    category: "Cooling",
    brand: "Noctua",
    description: "Premium dual-tower air cooler with exceptional reliability.",
    price: 149,
    msrp: 149,
    specs: { tdp: "250W", architecture: "Air", memory: "Dual 140mm" },
    tags: ["Air Cooling", "Quiet"],
    aiScore: 80,
  },

  // Additional GPUs (AMD Radeon AI-focused)
  {
    id: "rx-7900-xtx",
    name: "AMD Radeon RX 7900 XTX",
    category: "GPU",
    brand: "AMD",
    description: "24GB RDNA 3 flagship for ROCm and open-source AI workflows.",
    price: 999,
    msrp: 999,
    specs: { vram: "24GB GDDR6", cuda: "6144", tensor: "192", tdp: "355W", tflops: "61 FP16", architecture: "RDNA 3" },
    tags: ["AMD", "ROCm", "24GB"],
    aiScore: 85,
  },
  {
    id: "rx-7900-xt",
    name: "AMD Radeon RX 7900 XT",
    category: "GPU",
    brand: "AMD",
    description: "20GB high-performance card for AI inference on open stacks.",
    price: 849,
    msrp: 899,
    specs: { vram: "20GB GDDR6", cuda: "5376", tensor: "168", tdp: "300W", tflops: "52 FP16", architecture: "RDNA 3" },
    tags: ["AMD", "ROCm", "20GB"],
    aiScore: 80,
  },
  {
    id: "rx-7800-xt",
    name: "AMD Radeon RX 7800 XT",
    category: "GPU",
    brand: "AMD",
    description: "16GB mid-range AMD option for budget-conscious AI dev.",
    price: 499,
    msrp: 499,
    specs: { vram: "16GB GDDR6", cuda: "3840", tensor: "120", tdp: "263W", tflops: "37 FP16", architecture: "RDNA 3" },
    tags: ["AMD", "ROCm", "16GB"],
    aiScore: 72,
  },
  {
    id: "rtx-4060-ti-16gb",
    name: "NVIDIA GeForce RTX 4060 Ti 16GB",
    category: "GPU",
    brand: "NVIDIA",
    description: "Efficient entry AI card with useful 16GB frame buffer.",
    price: 449,
    msrp: 499,
    specs: { vram: "16GB GDDR6", cuda: "4352", tensor: "136", tdp: "165W", tflops: "23 FP16", architecture: "Ada Lovelace" },
    tags: ["RTX 40", "16GB", "Entry"],
    aiScore: 68,
  },
  {
    id: "rtx-6000-ada",
    name: "NVIDIA RTX 6000 Ada Generation",
    category: "GPU",
    brand: "NVIDIA",
    description: "48GB flagship workstation GPU for professional AI development.",
    price: 8999,
    msrp: 8999,
    specs: { vram: "48GB GDDR6 ECC", cuda: "18176", tensor: "568", tdp: "300W", tflops: "91 FP16", architecture: "Ada Lovelace" },
    tags: ["Workstation", "48GB", "ECC"],
    aiScore: 96,
  },

  // Additional CPUs
  {
    id: "ryzen-7-7800x3d",
    name: "AMD Ryzen 7 7800X3D",
    category: "CPU",
    brand: "AMD",
    description: "8-core 3D V-Cache CPU for low-latency inference coordination.",
    price: 369,
    msrp: 449,
    specs: { cores: "8", threads: "16", clock: "4.2 / 5.0 GHz", tdp: "120W", memory: "Dual-Channel DDR5", socket: "AM5" },
    tags: ["Ryzen 7", "3D V-Cache"],
    aiScore: 74,
  },
  {
    id: "ryzen-5-7600x",
    name: "AMD Ryzen 5 7600X",
    category: "CPU",
    brand: "AMD",
    description: "6-core budget AM5 option for single-GPU AI stations.",
    price: 199,
    msrp: 299,
    specs: { cores: "6", threads: "12", clock: "4.7 / 5.3 GHz", tdp: "105W", memory: "Dual-Channel DDR5", socket: "AM5" },
    tags: ["Ryzen 5", "Budget"],
    aiScore: 65,
  },
  {
    id: "core-i7-14700k",
    name: "Intel Core i7-14700K",
    category: "CPU",
    brand: "Intel",
    description: "20-core desktop CPU for balanced AI and productivity.",
    price: 419,
    msrp: 419,
    specs: { cores: "20", threads: "28", clock: "3.4 / 5.6 GHz", tdp: "125W", memory: "Dual-Channel DDR5", socket: "LGA1700" },
    tags: ["Core i7", "Desktop"],
    aiScore: 75,
  },
  {
    id: "core-i5-14600k",
    name: "Intel Core i5-14600K",
    category: "CPU",
    brand: "Intel",
    description: "14-core value Intel option for entry AI workstations.",
    price: 329,
    msrp: 329,
    specs: { cores: "14", threads: "20", clock: "3.5 / 5.3 GHz", tdp: "125W", memory: "Dual-Channel DDR5", socket: "LGA1700" },
    tags: ["Core i5", "Value"],
    aiScore: 68,
  },

  // Additional Motherboards
  {
    id: "asrock-x870-taichi",
    name: "ASRock X870 Taichi",
    category: "Motherboard",
    brand: "ASRock",
    description: "Premium AM5 board with reinforced PCIe 5.0 slots.",
    price: 499,
    msrp: 549,
    specs: { socket: "AM5", memory: "DDR5", channels: "Dual", architecture: "X870" },
    tags: ["AM5", "Premium"],
    aiScore: 77,
  },
  {
    id: "msi-pro-z790-a",
    name: "MSI PRO Z790-A WIFI",
    category: "Motherboard",
    brand: "MSI",
    description: "Reliable LGA1700 board for Core i7/i9 builds.",
    price: 219,
    msrp: 249,
    specs: { socket: "LGA1700", memory: "DDR5", channels: "Dual", architecture: "Z790" },
    tags: ["LGA1700", "Mainstream"],
    aiScore: 71,
  },
  {
    id: "gigabyte-b650-aorus-elite",
    name: "Gigabyte B650 AORUS Elite AX",
    category: "Motherboard",
    brand: "Gigabyte",
    description: "Cost-effective AM5 board with PCIe 4.0 x16 for GPUs.",
    price: 189,
    msrp: 229,
    specs: { socket: "AM5", memory: "DDR5", channels: "Dual", architecture: "B650" },
    tags: ["AM5", "Value"],
    aiScore: 69,
  },

  // Additional RAM
  {
    id: "corsair-vengeance-64-5600",
    name: "Corsair Vengeance 64GB (2x32GB) DDR5-5600",
    category: "RAM",
    brand: "Corsair",
    description: "Standard 64GB kit for budget AI workstations.",
    price: 189,
    msrp: 219,
    specs: { memory: "64GB (2x32GB)", clock: "5600 MT/s", architecture: "DDR5" },
    tags: ["64GB", "DDR5"],
    aiScore: 72,
  },
  {
    id: "gskill-trident-64-6000",
    name: "G.Skill Trident Z5 64GB (2x32GB) DDR5-6000",
    category: "RAM",
    brand: "G.Skill",
    description: "Fast 64GB kit optimized for AM5 platforms.",
    price: 209,
    msrp: 249,
    specs: { memory: "64GB (2x32GB)", clock: "6000 MT/s", architecture: "DDR5" },
    tags: ["64GB", "DDR5"],
    aiScore: 74,
  },

  // Additional Storage
  {
    id: "wd-black-sn850x-4tb",
    name: "WD Black SN850X 4TB NVMe",
    category: "Storage",
    brand: "Western Digital",
    description: "High-performance gaming SSD excellent for AI datasets.",
    price: 279,
    msrp: 349,
    specs: { memory: "4TB", bandwidth: "7,300 MB/s", architecture: "PCIe 4.0 x4" },
    tags: ["NVMe", "Gaming"],
    aiScore: 85,
  },
  {
    id: "sabrent-rocket-4-plus-8tb",
    name: "Sabrent Rocket 4 Plus 8TB",
    category: "Storage",
    brand: "Sabrent",
    description: "Massive 8TB capacity for large model storage.",
    price: 899,
    msrp: 1099,
    specs: { memory: "8TB", bandwidth: "7,100 MB/s", architecture: "PCIe 4.0 x4" },
    tags: ["NVMe", "8TB"],
    aiScore: 88,
  },
  {
    id: "seagate-firecuda-530-4tb",
    name: "Seagate FireCuda 530 4TB",
    category: "Storage",
    brand: "Seagate",
    description: "Reliable high-speed SSD with long warranty.",
    price: 349,
    msrp: 449,
    specs: { memory: "4TB", bandwidth: "7,300 MB/s", architecture: "PCIe 4.0 x4" },
    tags: ["NVMe", "Reliable"],
    aiScore: 84,
  },

  // Additional PSUs
  {
    id: "be-quiet-dark-power-13-1000w",
    name: "be quiet! Dark Power 13 1000W",
    category: "PSU",
    brand: "be quiet!",
    description: "Silent Titanium PSU for noise-sensitive AI labs.",
    price: 329,
    msrp: 369,
    specs: { tdp: "1000W", architecture: "80+ Titanium", memory: "ATX 3.0" },
    tags: ["1000W", "Silent"],
    aiScore: 85,
  },
  {
    id: "corsair-rm1200x-shift",
    name: "Corsair RM1200x SHIFT",
    category: "PSU",
    brand: "Corsair",
    description: "Side-connect 1200W PSU for cleaner cable management.",
    price: 249,
    msrp: 299,
    specs: { tdp: "1200W", architecture: "80+ Gold", memory: "ATX 3.0" },
    tags: ["1200W", "Side Connect"],
    aiScore: 82,
  },
  {
    id: "evga-supernova-1600-t2",
    name: "EVGA SuperNOVA 1600 T2",
    category: "PSU",
    brand: "EVGA",
    description: "Legacy 1600W Titanium PSU still popular for 4-GPU builds.",
    price: 549,
    msrp: 599,
    specs: { tdp: "1600W", architecture: "80+ Titanium", memory: "ATX 2.4" },
    tags: ["1600W", "Legacy"],
    aiScore: 87,
  },

  // Additional Cooling
  {
    id: "corsair-icue-h170i-elite",
    name: "Corsair iCUE H170i ELITE LCD",
    category: "Cooling",
    brand: "Corsair",
    description: "420mm AIO with LCD display for Threadripper builds.",
    price: 289,
    msrp: 329,
    specs: { tdp: "350W+", architecture: "AIO", memory: "420mm radiator" },
    tags: ["AIO", "LCD"],
    aiScore: 83,
  },
  {
    id: "nzxt-kraken-elite-360",
    name: "NZXT Kraken Elite 360",
    category: "Cooling",
    brand: "NZXT",
    description: "360mm AIO with customizable display for high-end builds.",
    price: 279,
    msrp: 299,
    specs: { tdp: "280W+", architecture: "AIO", memory: "360mm radiator" },
    tags: ["AIO", "Display"],
    aiScore: 79,
  },
];

export const products: Product[] = seedProducts.map((item) => ({
  ...item,
  imageUrl: item.imageUrl ?? getProductImage(item),
  merchants: createMerchants(item.query ?? item.name, item.price),
  recommended: item.recommended ?? (item.aiScore ?? 0) >= 84,
  availability: item.availability ?? "In Stock",
}));

export const getProductById = (id: string): Product | undefined => {
  return products.find((product) => product.id === id);
};

export const getProductsByCategory = (category: Product["category"]): Product[] => {
  return products.filter((product) => product.category === category);
};

export const getRecommendedProducts = (): Product[] => {
  return products.filter((product) => product.recommended);
};

export const getInStockProducts = (): Product[] => {
  return products.filter((product) => product.availability === "In Stock");
};
